### ISSUE TITLE
But on 'Установка пакета обновления ядра Linux

### ISSUE THREAD

**Issue by akalightowl** [MicrosoftDocs/WSL.ru-RU#7]
[Введите отзыв здесь]
Bug on html layout after id="install-the-linux-kernel-update-package" tag. I think content in div section shouldn't be wrapper like a code. It's content not a code. 

![image](https://user-images.githubusercontent.com/21196900/81053225-67416400-8ecd-11ea-8787-322c272165cf.png)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Обновление ядра Linux в WSL 2](https://docs.microsoft.com/ru-ru/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL.ru-ru/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @akalightowl
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @akalightowl 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged. 

Please review issue https://github.com/MicrosoftDocs/WSL/issues/596
For this reason, we are closing this issue since it is duplicated. 


Kind regards, 

Microsoft DOCS International Team
